export const FILL_INITIAL_STATE = 'FILL_INITIAL_STATE',
  INCREMENT_STOCK = 'INCREMENT_STOCK',
  DECREMENT_STOCK = 'DECREMENT_STOCK',
  INCREMENT_AMOUNT = 'INCREMENT_AMOUNT',
  DECREMENT_AMOUNT = 'DRECREMENT_AMOUNT',
  CHECKOUT = 'CHECKOUT'
